name: Deploy FastAPI App

on:
  push:
    branches:
      - test # Runs only when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_SERVER }} << 'EOF'
            cd  /projects/noted
            git pull origin main
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up --build -d
            docker system prune -af
          EOF
