name: Deploy FastAPI App

on:
  push:
    branches:
      - test # Runs only when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /projects/Noted
            git pull origin main
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up --build -d
            docker system prune -af
          EOF
