name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies & setup secrets
        run: |
          ls
          touch key.json server/.env
          cat << EOF > key.json
          {
            "type": "service_account",
            "project_id": "noted-5a4d1",
            "private_key_id": "${{ secrets.PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.PRIVATE_KEY }}",
            "client_email": "firebase-adminsdk-cayuu@noted-5a4d1.iam.gserviceaccount.com",
            "client_id": "${{ secrets.CLIENT_ID }}",
            "auth_uri": "https://accounts.google.com/o/oauth2/auth",
            "token_uri": "https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
            "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-cayuu%40noted-5a4d1.iam.gserviceaccount.com",
            "universe_domain": "googleapis.com"
          }
          EOF
          echo "${{ secrets.ENV }}" > server/.env
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt

      - name: Run tests
        run: |
          pytest server/tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/projects/Noted/server
          git pull origin main
          docker compose up --build -d
          docker system prune -af
          EOF
