name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies & setup secrets
        run: |
          touch server/key.json server/.env
          echo "${{ secrets.KEY }}" > server/key.json
          echo "${{ secrets.ENV }}" > server/.env
          python -m pip install --upgrade pip
          pip install -r server/requirements.txt


      - name: Run tests
        run: |
          ls server
          cat server/key.json
          pytest server/tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Set up SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ~/projects/Noted/server
          git pull origin main
          docker compose up --build -d
          docker system prune -af
          EOF
